#! /bin/bash
verbose=0
while :; do
    case $1 in
        -v|--verbose)
                verbose=1
                ;;
        *)               # Default case: No more options, so break out of the loop.
                break
    esac

    shift
done

if [ -z $CUDA_VISIBLE_DEVICES ];
    then echo must set CUDA_VISIBLE_DEVICES
    exit
fi

if [ $# -lt 1 ]; 
    then echo "train experiment.yaml ..."
    exit
fi

config=$1
shift
out=`echo $config | sed "s;.*/;;" | sed "s;\.yaml$;.out;"`
out_dir=`echo $config | sed "s/test_/frames_/" | sed "s;.*/;;" | sed "s;\.yaml$;;"`
echo invoke test --config=$config $@|& tee $out_dir/test.out
if [ $verbose == 1 ]; then
    nohup invoke test --config=$config $@|& tee $out_dir/test.out
else
    nohup invoke test --config=$config $ @>& $out_dir/test.out
fi
