#! /bin/bash
verbose=0
n=""
while :; do
    case $1 in
        -v|--verbose)
                verbose=1
                ;;
        -n|--nohup)
                n=nohup
                ;;

        *)               # Default case: No more options, so break out of the loop.
                break
    esac

    shift
done

if [ -z $CUDA_VISIBLE_DEVICES ];
    then echo must set CUDA_VISIBLE_DEVICES
    exit
fi

if [ $# -ne 1 ]; 
    then echo "train experiment.yaml"
    exit
fi

out=`echo $1 | sed "s;.*/;;" | sed "s;\.yaml$;.out;"`
if [ $verbose == 1 ]; then
    $n invoke train --config=$1 |& tee $out 
else
    $n invoke train --config=$1 >& $out 
fi
